// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzeriaNicDen.Data;

#nullable disable

namespace PizzeriaNicDen.Migrations
{
    [DbContext(typeof(PizzeriaContext))]
    [Migration("20261007081844_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PizzeriaNicDen.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaleImagine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingrediente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pret30cm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoriNutritionale30cm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizze");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.PizzaFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Pret50cm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoriNutritionale50cm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId")
                        .IsUnique();

                    b.ToTable("PizzeFamily");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.PizzaFamily", b =>
                {
                    b.HasOne("PizzeriaNicDen.Models.Pizza", "Pizza")
                        .WithOne("VariantaFamily")
                        .HasForeignKey("PizzeriaNicDen.Models.PizzaFamily", "PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.Pizza", b =>
                {
                    b.Navigation("VariantaFamily");
                });
#pragma warning restore 612, 618
        }
    }
}
