// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzeriaNicDen.Data;

#nullable disable

namespace PizzeriaNicDen.Migrations
{
    [DbContext(typeof(PizzeriaContext))]
    [Migration("20261008104034_AdaugaAnunturi")]
    partial class AdaugaAnunturi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PizzeriaNicDen.Models.Anunt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activ")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInceput")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSfarsit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Anunturi");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.AprecierePizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("AprecieriPizze");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaleImagine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingrediente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pret30cm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoriNutritionale30cm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizze");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaleImagine = "/img/margherita.jpg",
                            Ingrediente = "Sos de roșii, mozzarella fior di latte, busuioc proaspăt, ulei de măsline",
                            Nume = "Margherita",
                            Pret30cm = 28.00m,
                            ValoriNutritionale30cm = "250 kcal / 100g"
                        },
                        new
                        {
                            Id = 2,
                            CaleImagine = "/img/diavola.jpg",
                            Ingrediente = "Sos de roșii, mozzarella, salam picant, ardei iute jalapeño",
                            Nume = "Diavola",
                            Pret30cm = 34.00m,
                            ValoriNutritionale30cm = "310 kcal / 100g"
                        },
                        new
                        {
                            Id = 3,
                            CaleImagine = "/img/nicden.jpg",
                            Ingrediente = "Sos de roșii, mozzarella, șuncă, ciuperci, măsline, bacon, ardei gras",
                            Nume = "Specialitatea Nic&Den",
                            Pret30cm = 38.00m,
                            ValoriNutritionale30cm = "290 kcal / 100g"
                        });
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.PizzaFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Pret50cm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoriNutritionale50cm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId")
                        .IsUnique();

                    b.ToTable("PizzeFamily");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PizzaId = 1,
                            Pret50cm = 50.00m,
                            ValoriNutritionale50cm = "250 kcal / 100g"
                        },
                        new
                        {
                            Id = 2,
                            PizzaId = 3,
                            Pret50cm = 65.00m,
                            ValoriNutritionale50cm = "290 kcal / 100g"
                        });
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.RecenziePizzerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAdaugare")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stele")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("Recenzii");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumarLogari")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilizatori");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.AprecierePizza", b =>
                {
                    b.HasOne("PizzeriaNicDen.Models.Pizza", "Pizza")
                        .WithMany("Aprecieri")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzeriaNicDen.Models.Utilizator", "Utilizator")
                        .WithMany("Aprecieri")
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.PizzaFamily", b =>
                {
                    b.HasOne("PizzeriaNicDen.Models.Pizza", "Pizza")
                        .WithOne("VariantaFamily")
                        .HasForeignKey("PizzeriaNicDen.Models.PizzaFamily", "PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.RecenziePizzerie", b =>
                {
                    b.HasOne("PizzeriaNicDen.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.Pizza", b =>
                {
                    b.Navigation("Aprecieri");

                    b.Navigation("VariantaFamily");
                });

            modelBuilder.Entity("PizzeriaNicDen.Models.Utilizator", b =>
                {
                    b.Navigation("Aprecieri");
                });
#pragma warning restore 612, 618
        }
    }
}
